### ISSUE TITLE
多人老师の化妆教学

### ISSUE THREAD

**Issue by Rinfair** [project-trans/RLE-wiki#105]
[多人老师的化妆教学](https://twitter.com/duoren6221/status/1641443603489902601)
授权已获取，需署名和整理

**Comment by Cryolitia** [comment]
链接已经失效

**Comment by BeiyanYunyi** [comment]
多人已经退网，链接亦无法访问，故关闭此 issue。

**Comment by Cryolitia** [comment]
@BeiyanYunyi 能联系上她嘛
