### ISSUE TITLE
绒布球猫猫の穿搭教学

### ISSUE THREAD

**Issue by Rinfair** [project-trans/RLE-wiki#107]
[绒布球猫猫的穿搭教学](https://twitter.com/xiaomeijunww/status/1645827692644941825)
授权已获取，需署名

**Comment by Cryolitia** [comment]
@MikiLin-wiviw 哪来的猫，抓回来关笼子

**Comment by septs** [comment]
https://threadreaderapp.com/thread/1645827692644941825.html
