### ISSUE TITLE
可否添加一个hook使注释不会被渲染

### ISSUE THREAD

**Issue by LiAlH4-Tr** [project-trans/RLE-wiki#147]
可否对代码进行一些更改，使以下格式的注释不被渲染
> ::: xxx
xxxxxx
:::

**Comment by el-psy** [comment]
markdown-it-container ?

**Comment by LiAlH4-Tr** [comment]
> markdown-it-container ?

似乎可以，不过抱歉我不熟悉js，不知道怎么把这个插件引入这个项目

**Comment by BeiyanYunyi** [comment]
> 似乎可以，不过抱歉我不熟悉js，不知道怎么把这个插件引入这个项目

不可以。这个插件是实现

```markdown
:::note
这样的东西
:::
```

的渲染的，不是取消

```markdown
> :::note
这样的东西
:::
```

的渲染的。要改我估计要自己写

**Comment by LiAlH4-Tr** [comment]
感谢指正

> > 似乎可以，不过抱歉我不熟悉js，不知道怎么把这个插件引入这个项目
> 
> 这个插件不可以。恰恰相反，这个插件就是实现
> 
> ```
> :::note
> 这样的东西
> :::
> ```
> 
> 的渲染，而非取消其渲染的。并且 RLE.wiki 当前存在学校页面依赖了这个格式（不是注释！markdown 的注释格式和 HTML 相同）。例如[这个](https://rle.wiki/campus/NJU.html#%E4%BB%99%E6%9E%97%E6%A0%A1%E5%8C%BA-1)：
> 
> ![图片](https://user-images.githubusercontent.com/14120445/263472557-243525f4-3176-442c-aa26-3dc3a2768d53.png)
> 
> 原本的文档模板中包含 `:::note` 也正是为了渲染在页面上，亦有大学文档使用了 `:::note`。不能只为了改文档方便就不渲染这个

**Comment by el-psy** [comment]
源文档应该是这样的

With this plugin you can create block containers like:
```js
::: warning
*here be dragons*
:::
```
.... and specify how they should be rendered. If no renderer defined, <div> with container name class will be created:
```html
<div class="warning">
<em>here be dragons</em>
</div>
```

但我已经忘记它与vue之间的配合了。好像可以转换成一个组件。
只要我们把这个类或者组件的样式 定义为
```css
.display-none {
   display: none
}
```
之类的应该就可以了。
