### ISSUE TITLE
对于过时的内容应当如何处置

### ISSUE THREAD

**Issue by HalfSweet** [project-trans/RLE-wiki#157]
随着时代的发展，一些之前的时效性内容逐渐过时，例如疫情期间的临时管制措施等。

那这些内容应当如何处理呢，是应该隐藏起来还是直接删除，或者还有什么其他的解决方法吗。

**Comment by BeiyanYunyi** [comment]
可以设置一个梯度：

- 影响力持续至今的事情，尽管其已经结束，但为了因果关系完整，仍应予以保留。（举例：某校因为己亥冠病而取消了某政策，至今没有恢复，但存在恢复可能的，在等待两年、排除其恢复可能后，将“以前的政策”和“受己亥冠病防控措施影响”这两句按下方处理）
- 已无影响力，但影响力消失不足两年的，予以折叠、标注过时
- 已无影响力，影响力消失满两年的，予以删除
