### ISSUE TITLE
江南大学

### ISSUE THREAD

**Issue by AnotherReader** [project-trans/RLE-wiki#168]
### 贡献者名称

匿名

### 学校名称

江南大学

### 地址位置

江苏省无锡市

### 宿舍独立卫浴

大部分宿舍有独卫（北区一些旧公寓没有），少部分宿舍有独立浴室，公共浴室状况未知

### 教学区第三卫生间

个别学院楼有，二教无，其余未知

### 军训减免

可凭医学材料减免

### 军训管不管头发

是

### 体育减免

可凭医学材料减免

### 医保的可用情况

是

### 校医院可用度

未知

### 校区分布

几乎全部学生位于蠡湖校区（无锡市滨湖区，位置较偏远），亦有位于宜兴的东氿校区（似乎是分开招生的？）
尽管学校主校区分为南北两区，实际上是一个整体，之所以分为南北两区是因为便于行政管理和教学生活设施的分配。
主校区位于无锡近郊，从机场打车过去大约需要50元以上，学校东门口亦有地铁站，虽略偏远但交通便利。
 ~~从北门出门过马路就是机厅~~
学校比较大，目测占地面积估计约3.5平方千米，快递点也零散分散在校园各处，如果不会骑车可以选择坐校园小公交（票价2元，校园卡8折）
无锡精卫中心离的有点远，非高峰期乘出租车约25分钟路程

### 体育课以及军训相关

- 体育课可凭借校医院开具的证明在体育中心申请保健班，校医院证明的办理如果持有三甲医院的含有「不宜剧烈运动」相关字样可以立刻在校医院处通过并抄一张校医院的诊断证明给你。是否适用于易性症暂不明确（按照过往经验还是尽量少对学校领导层出柜），校医院较为偏向本地医院，而无锡精卫对LGBT的友善程度似乎不算太高，笔者这里用的是抑郁症的诊断证明。

- 军训可用相同流程申请观训

### 宿舍相关

- 指派男性请慎重考虑江大理工科相关专业，此类专业大多数位于较旧的北区（个别宿舍楼还有臭名昭著的七人寝），选择专业时请务必注意。南区宿舍楼基本可保证独立卫生间和四人寝上床下桌
- 由于宿舍床位紧张，办理走读会要求退宿，附近房价不是很便宜，经济困难建议合租。

### LGBT+友好情况

辅导员大多数是年轻人，包容能力较强，目前遇到的学院相关工作人员未见有明显恐性少数，据同校一位MtF的情报，校医院一位女医生态度较差，另有一位男医生能够理解trans。

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by HalfSweet** [comment]
如果您这边方便的画，希望可以补充一下学校的具体地理位置和校区分布情况哦，感谢您的投稿~

**Comment by AnotherReader** [comment]
> 如果您这边方便的话，希望可以补充一下学校的具体地理位置和校区分布情况哦，感谢您的投稿~

已经编辑，感谢提醒。
