### ISSUE TITLE
关于「校园指南」必要性的讨论

### ISSUE THREAD

**Issue by septs** [project-trans/RLE-wiki#18]
1. 时效性问题，理论上教职工与校方的雇佣关系受到市场影响
   从实际运行的角度来说最终政策跟着人走（e.g: 你所遭遇的舍友、宿管、辅导员、导师、等）
   因此时效性方面理论上需要历届持续反馈/跟踪

2. 客观性问题，由于编著立场为一般为第一人称且本站编辑无法核实，故如果无明显表述问题则会接收
   因此接受多方来源时会造成全文无法自洽，对读者辨识信息有效性的能力提出了更高的要求

3. 功能性问题，由于高考志愿的工作流程问题
   因此实际上 **录取权** 归实际申报院校所有，
   再加之家属及实际情况（调剂）一般情况下无法完全尊重当事人的个人意志。

当然如果有因 MtF.wiki 影响高考志愿申报的，希望积极反馈。

**Comment by Lhcfl** [comment]
不应该有标注时间吗。以及，现在为什么时间全部是2022/7/31

**Comment by Chen03** [comment]
> > 板块开设之初是希望展现与跨性别会有关系的基础设施和规定政策等的情况。现在看来某些院校（如 <https://mtf.wiki/zh-cn/docs/campus/china/seu/>）开头的 表格式一览表 比较适合在 wiki 展示。
> > 
> > 许多主观感受的评价放在 wiki 确实不妥，我同意Kenchiu的看法
> > 
> > > ...但也并不是完全没有参考价值。所以我目前想法是把校园板块从Wiki中分离，而不是彻底删除
> 
> 支持这种干货，大学有没有第三卫生间，宿舍洗澡间有没有浴帘，医保怎么样之类的东西还是很需要给一个索引的。如果 mtf wiki 这边能有一个指导性的 checklist 模板我觉得会很好。主观性的内容可以慢慢分出去。

qs……这里有一只被华科的2折医保骗过去的（x），这些信息对于生存真的很重要
而且，大学已有的mtf数量，友好度等信息，也一定程度影响了生活的难度……
（友好度是指，“华科之前已经有过很多只mtf，所以辅导员那边也很体谅（虽然因人而异啦），而且校方是知道这个情况”什么的，这种相对客观的因素）

虽然很多人没办法左右自己的高考志愿，但是如果能提供一些信息，起码也不坏的样子……至少能在父母耳边吹吹风吧（小声
而且也可以给准备高考的大家一些奋斗的方向！在高三黑暗的时期可以成为精神支柱(｡･ω･｡)ﾉ♡

**Comment by septs** [comment]
@sauricat 如果可以，建议您起个头（即为设计一份 Checklist）

**Comment by CurrentWave-oyx** [comment]
校园指南感觉对已经入学的跨性别来说用处会更大一点。。。
比如不清楚学校医疗情况可能会导致在医疗资源上有更大的花费。。。
但是把容易带有主观色彩的校园指南用作高考填报志愿的参考有点太勉强了。。。
我觉得可以把对学校环境的主观感受和学校会提供的客观资源分离开。。。
可以在同一个界面。。。
客观资源为主要内容。。。
主观感受作为留言板块。。。
（虽然这样更像论坛而不是wiki。。。
