### ISSUE TITLE
东北大学

### ISSUE THREAD

**Issue by yjb152-yjb** [project-trans/RLE-wiki#191]
### RLE.wiki URL

https://rle.wiki/campus/NEU.html

### 内容

浑南通地铁了，五十分钟内就能进城！

学校有一个反跨群，反跨势力很强大

但是学校有一些友跨

rle建议，就是先想办法留长发就行，之后在打扮自己，可以偷偷买点女装

**Comment by BeiyanYunyi** [comment]
反跨群有些哈人……

**Comment by el-psy** [comment]
反跨群
我怀疑是否只有一个。

**Comment by yjb152-yjb** [comment]
> 反跨群
> 我怀疑是否只有一个。

只有一个确定的反跨群

**Comment by yjb152-yjb** [comment]
> 反跨群有些哈人……

是的，这个群存在了至少五年

**Comment by yubfyph** [comment]
可以要一下你的联系方式吗

**Comment by wentywenty** [comment]
改下吧，学校里的反跨群，都已经更新换代了，现在这群管理大多数都是我的朋友了，都渗透完了，不反跨了
书记，换了，反跨群，没了，空调，有了，六人寝，没了，楼内浴室，有了
这是最好的时代！欢迎大家报考东北大学！！！
