### ISSUE TITLE
新版 RLE.wiki 首页标题中英文空格问题

### ISSUE THREAD

**Issue by NebuDr1ft** [project-trans/RLE-wiki#260]
![submit1](https://github.com/project-trans/RLE-wiki/assets/141834038/bd54711b-65af-4f9e-86ff-d2d5b388b605)
![submit2](https://github.com/project-trans/RLE-wiki/assets/141834038/59736a70-ce5c-4ee5-8627-8de2c415f7eb)

新版 RLE.wiki 首页标题不符合中英文空格规范。建议变更：

> 一份RLE指北 -> 一份 RLE 指北

**Comment by LittleSound** [comment]
在 https://github.com/project-trans/RLE-wiki/commit/cf283134ca28415a043787837c10536349da4cc4 中修复
