### ISSUE TITLE
RLE 边界在哪里

### ISSUE THREAD

**Issue by septs** [project-trans/RLE-wiki#29]
本站是否适合开设以下内容

1. 脱毛工具的使用及护理
   包括但不限于：物理脱毛、化学脱毛、激光脱毛
2. 美妆资源索引
   包括但不限于：博主、教程、化妆品科普、等
3. 伪声资源索引
   包括但不限于：教程、音频片段、等

**Comment by Fe3O4-Git** [comment]
感觉如果建立子目录的话应该可以(?)
比如 docs.rle.wiki/mtf 这样(?)

**Comment by anyuzu99** [comment]
我覺得可以做一個類目科普和推薦關注的鏈接。具體使用方法可能需要慢慢補充。

**Comment by LeeGuanLi** [comment]
个人感觉很适合

**Comment by CurrentWave-oyx** [comment]
个人感觉非常适合。。。
