### ISSUE TITLE
Bug: Header 图标缺失

### ISSUE THREAD

**Issue by BeiyanYunyi** [project-trans/RLE-wiki#312]
![图片](https://github.com/project-trans/RLE-wiki/assets/14120445/bc706276-e542-45d8-a439-45bbd1f88bc7)

似乎是 Update deps 合并以后出现的。原因似乎是 UnoCSS 的不正确配置，待查。

**Comment by BeiyanYunyi** [comment]
![图片](https://github.com/project-trans/RLE-wiki/assets/14120445/d4b3fac0-7157-48db-ac4b-3b9880aec91e)

**Comment by BeiyanYunyi** [comment]
在安装 `@iconify-json/carbon` 和 `@iconify-json/icon-park-outline` 后，仍剩下一些图标无法被加载：

![图片](https://github.com/project-trans/RLE-wiki/assets/14120445/d81eef9f-3b68-42fd-9390-091c6a024587)

**Comment by LittleSound** [comment]
will fix at integrations v2.0
