### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by njujimbo** [project-trans/RLE-wiki#342]
想到几个格式上的小问题
也可能是我不会操作（）

①
![image](https://github.com/project-trans/RLE-wiki/assets/144367787/3c8088f9-da75-4678-8df9-dd073a76194d)
作者的最后似乎一直有个“匿名”，而且没法编辑把它去掉
②
![image](https://github.com/project-trans/RLE-wiki/assets/144367787/2bc349a3-ead1-4360-906a-a8ecf95626d6)
段落可以设置右边也对齐吗（
③
建议第一行恢复显示“字数与预计阅读时间”，就像之前有的那样，感觉挺有用的（

**Comment by BeiyanYunyi** [comment]
1. 预期行为
2. 浏览器排版限制应该不太能做到（似乎有一个非常新的 CSS 特性能做到？）
3. 这个可以有

**Comment by Leetfs** [comment]
_第三条我试试_ ，或许也可以通过 Frontmatter 控制

**Comment by Cryolitia** [comment]
1. 要不然把匿名换成等吧，现在有些人还会在metadata里面自己写匿名或者等，太混乱了

**Comment by BeiyanYunyi** [comment]
@Leetfs 

Refers to: https://github.com/BeiyanYunyi/Astro-blog-Lithium/commit/3a1d98ab8fd00f2e169fe1734a7a574a205e2668#diff-18066b9f47a971ce0bb57a373d18faa1673be29923c948f4b3b4acf79ca09219

**Comment by Leetfs** [comment]
换成等好像也怪怪的）

我研究一下能不能让匿名在不该出现的时候不出现

**Comment by njujimbo** [comment]
![image](https://github.com/user-attachments/assets/cf0f8106-55af-49ab-9edd-af4e30d3a086)
![image](https://github.com/user-attachments/assets/2af66d61-3e95-427c-8371-77da1f55fbe2)
这两种是不是有点怪（小声）

**Comment by Cryolitia** [comment]
@Leetfs 匿名是在所有页面都一定要出现的，这是feature

**Comment by Leetfs** [comment]
CC @njujimbo 

一和三已修改，正在走 Review 流程。

第二条需要用 CSS， `<div class="justify-align">     </div>`

如图

![image](https://github.com/user-attachments/assets/e1db8bac-b449-4717-820d-ce16b5c2ff68)

但不同的平台对内联 CSS 的支持和处理方式有所不同，不利于后续迁移，不建议使用。

**Comment by BeiyanYunyi** [comment]
> 第二条需要用 CSS， `<div class="justify-align"> </div>`

应为：

```html
<div class="text-justify"> </div>
```

[兼容性](https://developer.mozilla.org/zh-CN/docs/Web/CSS/text-align#%E6%B5%8F%E8%A7%88%E5%99%A8%E5%85%BC%E5%AE%B9%E6%80%A7)意外地还不错，可以考虑在文章容器样式中加入，如：

```css
.vp-doc {
  text-align: justify;
}
```

**Comment by Leetfs** [comment]
第二条一起合到 PR 里面了，效果还不错

![image](https://github.com/user-attachments/assets/dba498b2-58ac-48bf-be8d-8f6cf291fcf1)

CC @BeiyanYunyi  @njujimbo
