### ISSUE TITLE
针对 MtF 的长发养成指南

### ISSUE THREAD

**Issue by septs** [project-trans/RLE-wiki#36]
https://lhcfl.github.io/2022/08/06/long-hair/

CC @Lhcfl 本站将在尊重贵站 CC-BY-SA-3.0 的前提下重新调整结构以更好的阅读体验呈现并发表，请悉知

**Comment by Lhcfl** [comment]
可以。但记住某论坛的对应帖子不是CC-BY-SA3.0的，其中的一切图片不允许引用。

**Comment by yanjianyecao** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
