### ISSUE TITLE
南京信息工程大学的宿舍

### ISSUE THREAD

**Issue by ddzzkunye** [project-trans/RLE-wiki#389]
这个是我的小学同学，他在南京信息工程大学  
![](https://github.com/user-attachments/assets/6d98b75c-69bf-45ef-b18f-f9855931787b)

**Comment by ddzzkunye** [comment]
补充一下，他在浦口地铁站的校区。

**Comment by BeiyanYunyi** [comment]
据我了解，无独卫的宿舍并非只有不要暖气才会被分到。2021 级大气科学大类法律男性会被分到一个古建筑保护宿舍（忘记沁多少了），无独卫。但情况也可能有变，需要和你这位同学核实一下。

**Comment by ddzzkunye** [comment]
> 据我了解，无独卫的宿舍并非只有不要暖气才会被分到。2021 级大气科学大类法律男性会被分到一个古建筑保护宿舍（忘记沁多少了），无独卫。但情况也可能有变，需要和你这位同学核实一下。

他还在药效上呢，你要是要找他核实的话，我可以把他id给你

**Comment by BeiyanYunyi** [comment]
id 可以发送邮件到 rlewiki@project-trans.org。

**Comment by BeiyanYunyi** [comment]
经沟通，该条目暂维持现状，等待更多信源反馈。
