### ISSUE TITLE
关于重庆大学

### ISSUE THREAD

**Issue by Pochinki98** [project-trans/RLE-wiki#444]
### RLE.wiki URL

https://rle.wiki/campus/CQU

### 内容

1、C区目前的所谓成人教育已经完全停办，参见<a href="http://www.cce.cqu.edu.cn/info/1727/6596.htm">此处</a>。目前C区主要分配给建立不久的医学院使用。

2、本科新生若属文科类（如马克思主义哲学和法学新闻类等）将被分配在A区，医学类本科新生应该是直接分配在C区。

3、重庆大学今年的军训实际只有两周，实际操作中并没有要求强制剪发（但是可能会扣分，不过对成绩影响不大）。
前些年的军训主要由重庆的某士官学校（专科）负责，客观来讲由于该士官学校学生素质普遍不高导致其所派出的军训教官（大都由该士官学校的高年级学生担任）素质相对较低且脾气相对暴戾。近两年来已经更换由陆军军医大学的高年级本科生担任教官，教官管理相对地宽松且素质也相对以往较高，目前军训时间减半，强度相对下降。

**Comment by Leetfs** [comment]
@Pochinki98 感谢反馈
