### ISSUE TITLE
文华学院

### ISSUE THREAD

**Issue by meltingManner** [project-trans/RLE-wiki#471]
### 贡献者名称与联系方式

暮雨

### 贡献者联系方式

QQ:1903931594

### 学校概述

文华学院是 2003 年创建的民办普通高等院校，前身是华中科技大学文华学院，2014 年转设为独立本科高校。位于武汉东湖新技术开发区 “武汉・中国光谷” 腹地，毗邻东湖。学校占地 1845 亩，全日制在校生 18135 人，教师千余人。设有 8 个学部，有 44 个本科和 8 个专科专业，涵盖多学科门类，有众多国家级、省级学科专业建设点。教学成果丰硕，有国家级、省级一流本科课程，学生在专利、创新创业、竞赛等方面表现出色，还有省级教学相关基地和团队。与多国高校建立校际合作关系。学校社会声誉良好，在各类民办高校排行榜中成绩优异。

### 地理位置及交通

湖北省武汉市东湖高新技术开发区文华园路 有两个校区 所有学生在光谷校区上课 ps:另一个校区我至今都没有去过
北校门出门步行800米就可以到佳园路地铁站,往天河机场方向坐到中山公园b2 出口出去走一km就可以去见xx开小证?

### 军训与体育

军训14天 不管头发,凭生理或精神证明可以免除军训,ps(军训免训需要写10篇1500字的读后感)体育课男女一起上,强度看自己选的项目.本人选的体育舞蹈,运动量一般.体测凭医生开具证明可以免除 ps:本人找李赋开了一个不适宜剧烈运动! 每个学期要求30次的乐跑,乐骑(笑)每次要求1.6km

补充军训不是很严,可以装点小病去校医院室,按照规定请假必须要求导员同意,并当天附上1500字读后感 ps:不过可以直接装病给教官,教官同意休息后直接溜回宿舍?

### 宿舍情况与基础设施

都是四人间,上床下桌,独立卫浴,没有洗衣机,要去楼层公共洗衣间,洗一次衣服4-5块钱,衣服都是晾在屋内,有点尴尬,吹风机0.1元一分钟,洗澡热水一分钟一块钱,晚上12点断热水,夏令时不熄灯,冬令时每天晚上23点至隔天6点断电,宿舍限电1000w 洗衣间有几个插座熄灯以后可以去偷电(

### 医疗资源

不能开局激素证明校医院就是很小的一个诊所,只能看基础的感冒发烧之类的不要期待有hrt药物,校内医院医保报销比例较高,校外医保保险有限

### LGBT 友善梗概

导员中立偏友跨?本人是信息学部学生,最开始给导员提交的证明上写明了性别障碍? 在导员的帮助下办理了军训免训,不上早晚自习,选择性帮我逃课?还给我约了学校的心理咨询中心好多次. 值得一提的是,学校心理咨询中心的办公桌上插着一面LGBT旗帜,至于心理咨询师挺友善的(个人感觉 不过没怎么和我谈性别焦虑的问题 本校毕业或在校xyn分布较少

### 其他

补充:未设第三卫生间
体育课无法协商减免,军训可以划水(
_No response_

### 以 CC-BY-SA 4.0 协议分发

- [x] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Leetfs** [comment]
感谢贡献， 辛苦补充下空缺处的信息

![image](https://github.com/user-attachments/assets/a4fa2638-ea7b-4f9f-a050-5443b6e75865)

**Comment by meltingManner** [comment]
补充了哦

**Comment by meltingManner** [comment]
> 感谢贡献， 辛苦补充下空缺处的信息
> 
> ![image](https://private-user-images.githubusercontent.com/50666532/381548274-a4fa2638-ea7b-4f9f-a050-5443b6e75865.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNDcwMDAsIm5iZiI6MTczMDM0NjcwMCwicGF0aCI6Ii81MDY2NjUzMi8zODE1NDgyNzQtYTRmYTI2MzgtZWE3Yi00ZjlmLWEwNTAtNTQ0M2I2ZTc1ODY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDAzNTE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMzVmM2IxZTAwNDYyYWRkYTk4ZWMxNGNlZDJjMjg1ODNhZjQxNjQzNmMwZTliZmI4Zjg3YjQ1NDEyZWM2YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wIqzVgTlY41MzLi7aFD-t6y0KryAV709_GBYzuiC4Cg)

补充了哦
