### ISSUE TITLE
海南大学（内容补充）

### ISSUE THREAD

**Issue by Arlia-Etoile** [project-trans/RLE-wiki#85]
### 学校名称

海南大学 (https://www.hainanu.edu.cn/) ，中文简称“海大”。<br> Hainan University, short for “HNU”. 

### 地址位置

学校有四个校区，分别是海甸、城西、观澜湖（在建）、儋州校区。
- 海甸校区位于 [海南省海口市美兰区人民大道58号](https://j.map.baidu.com/ae/DRd)
- 城西校区位于 [海南省海口市龙华区学院路4号](https://j.map.baidu.com/80/hxaJ)
- 观澜湖校区（在建）位于 [海口市龙华区龙桥镇羊山大道](https://j.map.baidu.com/f4/LuQc)
- 儋州校区位于 [海南省儋州市那大镇宝岛新村](https://j.map.baidu.com/b7/qM1)

学生将进入的校区：
- 除农学专业外，其它专业一本学生会进入位于海口的两个校区。
- 农学专业与二本专业进入位于儋州市的儋州校区学习至毕业。
- 一本理科专业中，大部分学生在入学时即进入海甸校区学习至毕业，部分理科学生（机械专业等）自2021年开始，大一第一学期进入城西校区学习，大二第二学期转回海甸校区学习至毕业。
- 一本文科专业，所有学生在大一学年进入城西校区学习，大二第一学期开始转回海甸校区学习至毕业。
- 观澜湖校区计划在建成之后，将管理学院与经济学院专业迁入，其它学院是否迁入暂不确定，一旦计划迁入，所迁入专业的学生将在入学时进入观澜湖校区学习至毕业。
- 观澜湖校区距离市区较远，且海口市无地铁，请未来可能会被迁入的同学注意。
- 城西校区占地面积狭小，基础设施落后，学生上课仅一栋9层高的教学楼，上楼电梯需要排队。
- 儋州校区情况待补充。

#### 1. 通用概况
- 所有校区宿舍配备独立卫生间与独立浴室，但除海甸校区紫荆宿舍楼外，所有宿舍无热水供应，洗澡必须前往楼外集体浴室。
- 集体浴室都带有独立隔断，不用担心洗澡时被他人看到，但隔断下部挡水效果差（地面到隔板约10cm），当你洗完澡时经常会被隔壁洗澡人的水溅到脚。
- 所有校区宿舍无公共卫生间。

#### 2. 城西校区概况
- 城西校区男子宿舍为上床下桌，6人宿。<br>女子宿舍除3-4层部分宿舍外，其余宿舍为上下床与通桌，3-4层部分宿舍为上床下桌。
- 宿舍楼为7层，不配备电梯，学校优先向高层宿舍安排学生。
- 宿舍几乎不限电，学校给出的限电为1500-1800w。
- 宿舍空间较小，物品堆积少的情况下不会拥挤，在物品堆积较多的情况下会很拥挤。且宿舍空间不定，有些宿舍面积更大，会配备全身镜；有些宿舍小，没有全身镜。
- 集体浴室在宿舍外，与两边宿舍距离较近。
- 浴室开放时间为晚上的16:00-23:00，学校所给出的中午开放时间浴室无热水，千万不要在中午前往浴室洗澡。
- 宿舍楼后为大马路，晚上经常有大型货车经过，且经常有偷车贼偷车失败搞得电动车报警声震天响，十分影响睡眠质量。

#### 3. 海甸校区概况

（1）海甸校区宿舍类型分为四人间（紫荆宿舍楼限定）、五人间、六人间。
         
- 四人间收费标准为1200元/年，在第一学期交学费时一同交。<br>1⃣️四人间住宿环境更好，且配备电梯，有独立卫浴及热水供应，洗澡不用去集体浴室。<br>2⃣️目前校内共3栋紫荆宿舍楼，2栋为女子宿舍，一栋为男子宿舍。
       
- 五人间收费标准为800元/年，在第一学期交学费时一同交。<br>1⃣️警告⚠️：五人间是住宿条件最差的宿舍，空间狭小且无上床下桌，室内稍微放点东西就会十分拥挤，属于消防检查的人看了都含泪开罚单的宿舍。<br>2⃣️基础设施条件极差
         
- 六人间收费标准为600元/年，在第一学期交学费时一同交。<br>1⃣️空间大小较城西校区男子宿舍稍小，但相比五人间要友好太多。<br>2⃣️四人为上下床+大通桌，二人为上床下桌。<br>3⃣️基础设施条件极差。

（2）宿舍楼好坏状况不定，最老的宿舍楼是1980年代的，海甸校区刚建成时期的古董楼。

（3）宿舍分配无自选，只能服从学校安排，宿舍好坏完全看运气。

（4）宿舍限电800w，一旦引发跳闸会被记处分、写检讨。

（5）集体浴室一般安排在几栋宿舍楼的中间，方便学生洗澡。

（6）宿舍大多位于校园内部，不靠近马路和闹市区，睡眠质量有保障。

#### 4. 观澜湖校区（在建）概况
- 所有宿舍均为上床下桌四人间，配备独立卫浴，可能会有热水入宿供应。

#### 5.儋州校区概况
- 待补充

### 教学区第三卫生间

校内无第三卫生间，仅有男、女两性别卫生间。

#### 1. 军训减免

军训可因病减免或不训，但需要出示三甲医院证明。

#### 2. 军训管不管头发

不管头发，但需要带军帽，集合时不戴帽子会被罚做俯卧撑。

#### 3. 军训时长

12天连训，中间不休息。

#### 4. 军训教官

各班及各专业教官为军队退伍返校的学长学姐；总教官可能为上面指派，各校区一名。

#### 5. 军训强度

（1）教官在军训开始时4-5天会折腾人，期间十分累，请做好准备。
（2）在度过前4-5天后，军训强度会降低
（3）不会出现下雨天被拉出来军训的情况，但如果是训练中遇到强度较小、降水时间短的太阳雨，会一直训练。

#### 6. 注意事项

- 军训所在时间段太阳很毒，请准备好防晒霜和水。
- 军训时会收手机，禁止拍照，更不要把照片发到外网，会直接被请喝茶。
- 军训服订购，请订购大1-2码的军训服，因为军训服的质量都很差，十分容易造成社死。

#### 2. 体育课上课形式
- 大一体育课统一由学校及老师安排课程，无法选择。
- 大二体育课可以选修，但限定生理性别，很多能混过的课程生理性别男的学生都不能选，且剩余课程的范围由教务处决定，有些课明明能排课，但教务处不给你排你就没法选修，比如游泳。
#### 4. 体育课考核难度：
- 大一体育课考核难度中等偏上，正常上课外加达标项目及格，总成绩及格不难。
- 大二体育课考核难度根据选修课程决定。
#### 5. 体育课减免
- 如是户外体育课，因病有证明减免成功率更高。
- 室内体育课（健身等），能够被减免的成功率更低，且下雨天，只要雨不大，就必须去上课。

### 医保的可用情况

- 目前已知消息是，抑郁症等精神疾病，只要在当地医院就诊大于等于半年，就可以在医院开具慢性病证明以享受医保报销。

- 由于2023年度海南医保收取金额提高，故有可能提供门诊就医取药报销，但目前不清楚，此项存疑。

### 校医院可用度

- 海甸校区医院：可做小手术，药品储备较充足。
- 城西校区医院：只有维生素片，校医院几乎不可用。
- 儋州校区医院：待补充。

#### 1. 食堂
- 海甸校区：<br>1⃣️食堂总数为13个，共分布在5个食堂楼中。<br>2⃣️菜品便宜，味道好吃，是方圆10km内物价最便宜的地方（没有在开玩笑）。<br>3⃣️饭点食堂经常找不到座位，需要拼桌。
- 城西校区：<br>1⃣️食堂总数为2个，共分布在2个食堂楼中。<br>2⃣️菜品昂贵，与校外同价。<br>3⃣️味道极其难吃，校外随便找个外卖都比食堂好吃。

#### 2. 学校环境
- 海甸校区：<br>1⃣️人很多，但好在校园够大，所以不是十分拥挤。<br>2⃣️学校教学设施更新较及时。
- 城西校区：<br>1⃣️人少，但由于只有一栋教学楼，上课时会十分拥挤。<br>2⃣️学校教学设施及建筑维护差，给人一种上中专的感觉。

### 教学质量

1. 公共课教学质量很差，基本每年学生评教，排在最后的都是公共课教师。
2. 专业课教学质量好，法律系教师（或法律专业毕业的教师）教学质量排在前列。
3. 城西校区高等数学教学质量奇差，某教师曾创下25%的年级不及格率（在此之前，最高纪录为3%）。
4. 部分选修课教师滥用权力，为难学生，例如设置较难的平时分考察制度，***每次上课***都必须点名半节课等。

#### 1. 转专业要求
- 仅在大一第一学期开放转专业，过时不候。
- 转专业比例为理科前50%，文科前30%。
- 通过转专业考试。

#### 2. 转专业后情况
- 转专业后，大一第二学期仍然跟旧专业一起上课，大二开始才学习新专业内容
- 大二开始后，大一和大二的课会一起上，课程安排十分频繁。
- 转专业后，若新专业某科目的学分高于旧专业相同科目，则必须重修。
- 直到大二第二学期才能彻底办完所有转专业的行政手续。

### 现状梗概

虽然校方管理本着“只要不死人，学校不管你”的态度，但依旧不推荐报考该学校。原因有下：
- 海口市奇高的物价以及过低的收入，导致生活费在3500元/月以下时必定捉襟见肘。
- 对文科学生不友好。第一年在城西校区纯粹是花钱给学校看园子，还必须接受奇差的高数教育，最后往往会因为高数分数而失去转专业资格。
- 快递往往会因为琼州海峡的原因延迟送达。尤其是在每年10-11月的台风季，台风稍微频繁，就会导致你一个月都收不到快递。
- 学校行政处理效率低下。曾有过大一奖学金大四才发，以及大一处分到考研前才记录的惊人案例。
- 学校过早开学与过晚放假。<br>1⃣️过晚放假：学校为上满20周行政历的课程，经常将学生考试时间故意拖延到20周前后，其实明明17-18周就能上完课考完试放学生回家，但学校死活拖时间不放人。<br>2⃣️过早开学：这个一般体现在寒假开学日期上，通常学校最多给学生30天假期，就会迫不及待宣布开学，强制要求学生返校。
- 教务处极其恶心人。<br>1⃣️每年选课系统必定崩溃，教务处去年修过之后也依旧会崩溃不止。<br>2⃣️有些课程明明有排课时间但就是不排，导致学生无法选到心仪课程。

### 以 CC-BY-SA 4.0 协议分发

- [X] 我同意以 CC-BY-SA 4.0 协议分发

**Comment by Arlia-Etoile** [comment]
#海南大学 #HNU #Update HNU

**Comment by Cryolitia** [comment]
请问是否需要署名

~~以及怎么你们和湖南大学都叫HNU~~

**Comment by Arlia-Etoile** [comment]
不需要署名
湖南大学那个，这我就不知道了

**Comment by ArtsEpiphany** [comment]
感谢投稿！有个问题还想和您确认一下，就是`转专业比例为理科前50%，文科前30%`应当怎样理解呢？这个“理科”“文科”是指高考时的文科试卷与理科试卷，还是当前专业属于文科还是理科，还是目标专业属于文科还是理科呢？这个排名是在当前专业的排名还是在目标专业的排名呢？

**Comment by Arlia-Etoile** [comment]
都是按专业算，看专业文理科属别，看专业排名，高考排名一点用不上（高考文理分科都取消了，怎么可能看高考）

**Comment by Rinfair-CSP-A016** [comment]
Closed due to Pull Request #98 or commit 7dabd83
